### PR TITLE
Skip azure test on other provider

### PR DESCRIPTION
**Pull request by tomahawk28**
Prior to https://github.com/giantswarm/giantswarm/issues/13971, I would like to make some tests here to skip depends on the provider.

### CODE REVIEW

**Comment by fiunchinho** [comment]
Some of these tests already [require an env var called `PROVIDER`](https://github.com/giantswarm/sonobuoy-plugin/blob/89b3d73581761ba1b8b27e0f6f38932240ff0056/pkg/provider/common.go#L14) with the provider to use. It'd be easier for you to check that instead.

**Comment by tomahawk28** [comment]
@fiunchinho Thanks, I update it to check env value instead. I will open this PR after testing in geckon; Thanks!

**Comment by tomahawk28** [comment]
Tested in `giraffe`

```    
<testcase classname="v5" name="Test_AzureClusterCR" time="0.000">
      <skipped message="    azurecluster_test.go:37: can&amp;#39;t run azure test in `aws` cluster, skipping"/>
    </testcase>
    <testcase classname="v5" name="Test_AzureMachinePoolCR" time="0.000">
      <skipped message="    azuremachinepool_test.go:36: can&amp;#39;t run azure test in `aws` cluster, skipping"/>
    </testcase>
```

**Comment by fiunchinho** [comment]
There are probably issues with the different CRDs. Also, [the tekton setup that runs these tests uses `godsmack` for azure, `gaia` for aws and `gorgoth` for kvm](https://github.com/giantswarm/test-infra/blob/80a8a65a650f8d222f86af5b5da33fc7f000a861/secrets/generate-standup-kubeconfig-secret.sh#L4-L6).

**Comment by tomahawk28** [comment]
Thanks, @fiunchinho Do you think I need to run tests there?

**Review by rossf7 — COMMENTED** [review]
Looks good! I'm happy when @fiunchinho is happy.

**Review by fiunchinho — APPROVED** [review]
LGTM

**Pull request merged**
